# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/htc/z4dug/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/htc/z4dug/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/htc/z4dug/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/htc/z4dug/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/htc/z4dug/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/htc/z4dug/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/htc/z4dug/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/htc/z4dug/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/htc/z4dug/proprietary/bin/thermald:system/bin/thermald \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athtcmd_ram.bin \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/athwlan.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/athwlan.bin \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/bdata.bin \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/fw-4.bin \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/nullTestFlow.bin \
    vendor/htc/z4dug/proprietary/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin:system/etc/firmware/ath6k/AR6003/hw2.1.1/utf.bin \
    vendor/htc/z4dug/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/htc/z4dug/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/htc/z4dug/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/htc/z4dug/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/htc/z4dug/proprietary/lib/libdivxdrmdecrypt.so:system/lib/libdivxdrmdecrypt.so \
    vendor/htc/z4dug/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/htc/z4dug/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/htc/z4dug/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/htc/z4dug/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/htc/z4dug/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/htc/z4dug/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/htc/z4dug/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/htc/z4dug/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/htc/z4dug/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/htc/z4dug/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/htc/z4dug/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/htc/z4dug/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/htc/z4dug/proprietary/lib/libmm-audio-resampler.so:system/lib/libmm-audio-resampler.so \
    vendor/htc/z4dug/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/htc/z4dug/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/htc/z4dug/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/htc/z4dug/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/htc/z4dug/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/htc/z4dug/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/htc/z4dug/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/htc/z4dug/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/htc/z4dug/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/htc/z4dug/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/htc/z4dug/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/htc/z4dug/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/htc/z4dug/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/htc/z4dug/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/htc/z4dug/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/htc/z4dug/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/htc/z4dug/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/htc/z4dug/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/htc/z4dug/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/htc/z4dug/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/htc/z4dug/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/htc/z4dug/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/htc/z4dug/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/htc/z4dug/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/htc/z4dug/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/htc/z4dug/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/htc/z4dug/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/htc/z4dug/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/htc/z4dug/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/htc/z4dug/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/htc/z4dug/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/htc/z4dug/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/htc/z4dug/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/htc/z4dug/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/htc/z4dug/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/htc/z4dug/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/htc/z4dug/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/htc/z4dug/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/htc/z4dug/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/htc/z4dug/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/htc/z4dug/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/htc/z4dug/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so
